version: "3.1"
services:
  mongo:
    image: mongo:4.4
    container_name: 'mongo-container'
    restart: always
    ports:
      - 27017:27017

  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/code
    container_name: 'api-tsc'
    command: npm run dev
    links:
      - mongo
